services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: beautycrm_app
    ports:
      - "8021:8000"   # Cambié el puerto externo para evitar conflicto
    volumes:
      - ./src:/var/www/html
      - composer-cache-beautycrm:/tmp/composer-cache
    depends_on:
      - mysql
    working_dir: /var/www/html

  node:
    image: node:20
    container_name: beautycrm_node
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
      - node_modules_beautycrm:/var/www/html/node_modules
    ports:
      - "5175:5173"   # Cambié el puerto externo para evitar conflicto
    command: sh -c "npm install && npm run dev"

  mysql:
    image: mysql:8.0
    container_name: beautycrm_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: beautycrm
      MYSQL_USER: beautycrm
      MYSQL_PASSWORD: beautycrm
    ports:
      - "3321:3306"   # Cambié el puerto externo para evitar conflicto
    volumes:
      - beautycrm_mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: beautycrm_phpmyadmin
    restart: always
    ports:
      - "8083:80"   # Cambié el puerto externo para evitar conflicto
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root

volumes:
  beautycrm_mysql_data:
  composer-cache-beautycrm:
  node_modules_beautycrm: